### ISSUE TITLE
Lab Report 1 Feedback

### ISSUE THREAD

**Issue by joy002** [hoz011/cse15l-lab-reports#1]
Here is your feedback for Lab Report 1:

- [x] All relevant URLs written as markdown links
- [x] All relevant code examples written with backticks (```)
   - Use backticks for the code example. For instance, `scp`, `ls`, etc.
   - please explain ls -lat in more detailed in part 3. Seems like your explanation can also apply to `ls -l`. Then what's the difference between `ls -lat` and `ls -l`? Think about what each flag(-l, -t, -a) do. Hint: try typing  `man ls` in your terminal to see the hint of each flag.
   - In step 6, cs15lwi22@ieng6.ucsd.edu is not a student account, you either just write down your student account or you want to put something like how you did in part 4: cs15lwi22_ _@ieng6.ucsd.edu to indicate student account has 2 other digits after cs15lwi22.
- [x] All screenshots correspond to the described steps
   - Missing a screenshot showing that there is no need to enter password after you set up keygen.
- [x] All titles of sections are formatted as headers or similar
- [x] Lab report is on its own page, not the index page
- [x] Last example counts keystrokes and shows how to run remotely saving time
   - Need to include the counts of keystrokes to show how running remotely saves time. 
- [x] Text is formatted in a way that was easy for grader to read

Additional comments from your grader:
Good job:)

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by joy002** [comment]
Hi, I reviewed your lab report. One more thing you still need to fix: use ` for the code instead of make it italic.

**Comment by hoz011** [comment]
Hello, I'm a little confused on which part needs to be written with backticks. I checked that all code snippets were using backticks (unless I missed one somewhere?) Is it the part in step 3 where I put the backticks inside the italics?

**Comment by hoz011** [comment]
I have fixed that part in step 3 and put the backticks outside of the italics. Will I still get a chance to get my grade updated? Here is the link to the page: https://hoz011.github.io/cse15l-lab-reports/lab-report-1-week-2.html

**Comment by joy002** [comment]
Ok! from the link you post to me, it seems like the backtick block didn't show up. However, when I go to your code, I saw you have add the backticks. So I have changed you grade, make sure you check it on gradescope. If there is any other problem please comment below.
