### ISSUE TITLE
Lab Report 2 Feedback

### ISSUE THREAD

**Issue by mrkylesmith** [hoz011/cse15l-lab-reports#2]
**Bug/Input 1**
- [x] Commit screenshot for bug/input 1
- [x] Link to test file for bug/input 1
- [x] Symptom shown as command + output for bug/input 1
- [x] Description of relationship between bug, symptom, and input for bug/input 1

**Bug/Input 2**
- [x] Commit screenshot for bug/input 2
- [x] Link to test file for bug/input 2
- [] Symptom shown as command + output for bug/input 2
- You should show the command in your screenshot
- [x] Description of relationship between bug, symptom, and input for bug/input 2

**Bug/Input 3**
- [x] Commit screenshot for bug/input 3
- [x] Link to test file for bug/input 3
- [] Symptom shown as command + output for bug/input 3
- - You should show the command in your screenshot
- [x] Description of relationship between bug, symptom, and input for bug/input 3

Additional comments from your grader:
Great job!  Just include the command used in your screenshots and otherwise looks good.

Feel free to comment below if you have any questions about the rubric/feedback.

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by hoz011** [comment]
Hi, I submitted a regrade request but I had a question.

For the screenshot of the command for issue 2, I couldn't manage to get a screenshot of the infinity loop with the command in one screenshot because the infinity loop error just kept printing out numbers and I couldn't scroll up that far. I just included the command I used in the write-up, is there another way I should do that? Thanks!

**Comment by mrkylesmith** [comment]
Hi, thanks for submitting a regrade request and making these changes, that looks good.  And for the command for issue 2 that looks okay, I just wanted to see the command that you used to produce that symptom. Looks good!  I have updated your score on gradescope.
